### ISSUE TITLE
Doesn't work on reference style link

### ISSUE THREAD

**Issue by blazeu** [JLongley/gatsby-remark-external-links#2]
With
```md
This is [GatsbyJS][ref] link

[ref]: https://www.gatsbyjs.org
```
The resulting HTML will be

```html
This is <a href="https://www.gatsbyjs.org">GatsbyJS</a> link
```

No attribute added, while the normal style (`[]()`) works as expected.

**Comment by blazeu** [comment]
Seems like it was fixed on https://github.com/JLongley/gatsby-remark-external-links/commit/e04b5f2726ec34a698b994a8f3ea60fe303b2215 but it's not published npm yet.

Ping @JLongley

**Comment by JLongley** [comment]
Oops! I've published it.
